#!/usr/bin/python3

import sys
from time import sleep
from subprocess import call as run

# year = sys.argv[1]
progname = sys.argv[1]
version = sys.argv[2]
testno = 0
if len(sys.argv) > 3:
    testno = int(sys.argv[3])

a = run(['./compile', progname, version])

if a == 255:
    print('Užduotis nerasta')
    exit()
elif a == 254:
    print('Nepavyko sukompiliuoti')
    exit()

if testno > 0:
    a = run(['./test', progname, version, str(testno)])
else:
    a = run(['./test', progname, version])

if a == 255:
    print('Užduotis nerasta')
    exit()
elif a == 254:
    print('Užduotis neturi testų')
    exit()