#!/usr/bin/python3

import os
import sys

year = sys.argv[1]
if len(sys.argv[2].split('-')) > 1:
    progname = sys.argv[2].split('-')[0]
    progclass = sys.argv[2].split('-')[-1]+'/'
else:
    print('Pasirinkite jau arba vyr')
    exit(-1)
version = sys.argv[3]
# print(progname, progclass, version)

try:
    foldname = os.popen('find . -type d -wholename "./{year}/*/{progclass}{progname}"'.format(progname=progname, progclass=progclass, year=year))
except IOError:
    print('Error on find')
    exit()

foldname = foldname.read().replace('\n','')
# print('fold:',foldname)
if foldname == '':
    exit(-1)

testfolder = '{foldname}/*testai'.format(foldname=foldname, progname=progname, progclass=progclass)

if testfolder == '':
    exit(-2)

testno = int(os.popen('ls {testfolder} | wc -l'.format(testfolder=testfolder)).read())//2
onetest = False
if len(sys.argv) > 4:
    testno = int(sys.argv[4])
    onetest = True

if not onetest:
    for i in range(testno):
        no = i+1
        ans = os.popen('cat {testfolder}/*.{testno}[p\-.]*in | {foldname}/sprendimai/{version}/bin/{pname}'.format(testfolder=testfolder, testno=str(no).zfill(2), pname=progname, version=version, foldname=foldname, progclass=progclass)).read()
        sol = os.popen('cat {testfolder}/*.{testno}[p\-.]*sol'.format(testfolder=testfolder, pname=progname, testno=str(no).zfill(2), progclass=progclass)).read()

        if str(ans).replace("\n", "") == str(sol).replace("\n", ""):
            print('Test #' + str(no).zfill(2) + ' ' + '\x1b[6;30;42m' + 'Success!' + '\x1b[0m')
        else:
            print('Test #' + str(no).zfill(2) + ' ' + '\x1b[6;30;41m' + 'Failed' + '\x1b[0m')
else:
    ans = os.popen('cat {testfolder}/*.{testno}[p\-.]*in | {foldname}/sprendimai/{version}/bin/{pname}'.format(testfolder=testfolder, testno=str(testno).zfill(2), pname=progname, version=version, foldname=foldname, progclass=progclass)).read()
    sol = os.popen('cat {testfolder}/*.{testno}[p\-.]*sol'.format(testfolder=testfolder, pname=progname, testno=str(testno).zfill(2), progclass=progclass)).read()
    if str(ans).replace("\n", "") == str(sol).replace("\n", ""):
        print('Test #' + str(testno).zfill(2) + ' ' + '\x1b[6;30;42m' + 'Success!' + '\x1b[0m')
    else:
        print('Test #' + str(testno).zfill(2) + ' ' + '\x1b[6;30;41m' + 'Failed' + '\x1b[0m')